routes/web.php
<?php
use \Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
    //     return view('welcome');
    // });
    
    
    //----------------------------------------------     ADMIN PAGE    ----------------------------------------------------//
    
    Auth::routes();
    // LOGOUT
    // Route::middleware(['role'])->group(function () {
        
        // });
        
  Route::get('login_auth', 'Auth\AuthController@getFormLogin')->name('login_auth');
  Route::post('login_auth', 'Auth\AuthController@submitLogin')->name('login_auth');
  Route::get('logout', 'Auth\AuthController@logout')->name('logout');

  Route::group(['middleware' => ['auth','role']], function () {
      Route::get('/admin/index', 'Admin\HomeController@index')->name('/admin/index');
      
      // CATEGORY
      Route::resource('/category', 'Admin\CategoryProductController');
      Route::get('/search_category', 'Admin\CategoryProductController@search')->name('search_category');
      
      // PRODUCT
      Route::resource('/product', 'Admin\ProductsController');
      Route::get('/search_product', 'Admin\ProductsController@search')->name('search_product');
      Route::get('export_products', 'Admin\ProductsController@export')->name('export_products');
      Route::post('import_products', 'Admin\ProductsController@import')->name('import_products');
      
      // CUSTOMER
      Route::resource('/customer', 'Admin\CustomersController');
      Route::get('/search_customer', 'Admin\CustomersController@search')->name('search_customer');
      
      // USERS
      Route::resource('user', 'Admin\UsersController');
      Route::get('/search_user', 'Admin\UsersController@search')->name('search_user');
      
      // ROLES
      Route::resource('role', 'Admin\RolesController');
      Route::get('/search_role', 'Admin\RolesController@search')->name('search_role');
      
      // PICTURES
      Route::resource('picture', 'Admin\PictureController');
      Route::get('/search_picture', 'Admin\PictureController@search')->name('search_picture');
      
      //ORDER
      Route::resource('order', "Admin\OrdersController");
      Route::get('/search_order', 'Admin\OrdersController@search');
      Route::get('/getOrderCurrent', 'Admin\OrdersController@getOrderCurrent')->name('getOrderCurrent');
      Route::get('/getOrderDone', 'Admin\OrdersController@getOrderDone')->name('getOrderDone');
      Route::get('/getOrderWait', 'Admin\OrdersController@getOrderWait')->name('getOrderWait');
      Route::get('/print_order/{checkout_code}', "Admin\OrdersController@print_order")->name("print_order");
      
      
      //CONTACT
      Route::resource('contact_admin', 'Admin\ContactController');
      Route::get('/search_contact', 'Admin\ContactController@search')->name('search_contact');
      
      //STATISTICS
      Route::get('/statistic/index', 'Admin\StatisticsController@index')->name('/statistic/index');
      Route::get('/statistic/order_pay', 'Admin\StatisticsController@getOrder')->name("/statistic/order_pay");
      Route::get('/statistic/comment_count', 'Admin\StatisticsController@getComment')->name("/statistic/comment_count");
      Route::get('/statistic/order_highlight', 'Admin\StatisticsController@getOrderHighlight')->name("/statistic/order_highlight");
      Route::get('/statistic/order_time', 'Admin\StatisticsController@getOrderTime')->name("/statistic/order_time");
      Route::get('/statistic/order_quarter', 'Admin\StatisticsController@getOrderQuarter')->name("/statistic/order_quarter");
      Route::get('/statistic/order_count', 'Admin\StatisticsController@getOrderCount')->name("/statistic/order_count");
      Route::get('/statistic/order_list/{month}/{year}', 'Admin\StatisticsController@getListOrderTime')->name("/statistic/order_list");


      // THỐNG KÊ DẠNG BIỂU DỒ
      Route::get('/statistic/chart/revenue', 'Admin\StatisticsController@Revenue')->name('revenue');
      Route::post('/statistic/chart/filter_by_date', 'Admin\StatisticsController@filter_by_date')->name('filter_by_date');
      Route::post('/statistic/chart/filter_by_month_year', 'Admin\StatisticsController@filter_by_month_year')->name('filter_by_month_year');
      Route::post('/statistic/chart/filter_by_year', 'Admin\StatisticsController@filter_by_year')->name('filter_by_year');
      Route::post('/statistic/chart/get_revenue_filter_date', 'Admin\StatisticsController@getRevenueFilterDate')->name('get_revenue_filter_date');
      Route::post('/statistic/chart/get_revenue_today', 'Admin\StatisticsController@getRevenueToday')->name('get_revenue_today');
      Route::post('/statistic/chart/filter_by_quater', 'Admin\StatisticsController@filter_by_quater')->name('filter_by_quater');
      
      
      // COMMENT
      Route::resource('comment', 'Admin\CommentsController');
      Route::get('/search_comment', 'Admin\CommentsController@search')->name('search_comment');
      
      // DISCOUNT
      Route::resource('discount', 'Admin\DiscountController');
      Route::get('/search_discount', 'Admin\DiscountController@search')->name('search_discount');
      
      //NEWS
      Route::resource('news', 'Admin\NewsController');
      Route::get('/search_new', 'Admin\NewsController@search')->name('search_new');
      
      //Excel
      Route::get('export', 'MyController@export')->name('export');
      Route::get('importExportView', 'MyController@importExportView');
      Route::post('import', 'MyController@import')->name('import');
      
    
  });
    // LANGUAGE
    Route::get('/language/{language}','Admin\LanguageController@index')->name('language.index');
  // Route::get('/admin/index', 'Admin\HomeController@index')->name('/admin/index')->middleware(['auth','role']);


  //----------------------------------------------     USER PAGE    ----------------------------------------------------//

  Route::get('/', 'User\HomeController@index')->name('index');
  Route::get('/search', 'User\HomeController@index')->name("search");
  Route::get('/listproduct/{id?}', 'User\ProductController@index')->name('listproduct');
  Route::get('/product_detail/{id?}', 'User\ProductDetailController@index')->name('product_detail');

  // SHOPPING CART
  Route::resource('cart', "User\CartController");
  Route::get('addcart/{id?}', "User\CartController@addCart")->name("addcart");
  Route::put('updateAll', "User\CartController@updateAll")->name("updateAll");

  //CHECK OUT

  
Route::get('get-district-list/{province_id}','User\CheckoutController@getDistrictByProvince');
Route::get('get-ward-list/{district_id}','User\CheckoutController@getWardByDistrict');

  Route::get('get_login_order', "User\CheckoutController@get_login_order")->name("get_login_order");
  Route::post('login_order', "User\CheckoutController@login_order")->name("login_order");
  Route::get('logout_checkout', "User\CheckoutController@logout_checkout")->name("logout_checkout");

  // Route::get('history', "User\CheckoutController@history")->middleware(['auth','history:user'])->name("history");
  Route::get('history', "User\CheckoutController@history")->name("history");
  Route::get('history_order_detail/{id?}', "User\CheckoutController@history_order_detail")->name("history_order_detail");

  Route::get('checkout', "User\CheckoutController@getFormPay")->name("checkout");
  Route::get('checkout_success', "User\CheckoutController@success")->name("checkout_success");
  Route::post('checkout', "User\CheckoutController@postFormPay")->name("checkout");

  Route::post('vnpay_payment', "User\CheckoutController@vnpay_payment")->name("vnpay_payment");


  // CONTACT
  Route::get('/contact', "User\ContactController@index")->name("contact");
  Route::post('/contact', "User\ContactController@saveContact")->name("contact");

  // COMMENT 
  Route::post('/comment/{id?}', "User\ProductDetailController@saveComment")->name("comment");


  // NEWS
  Route::get("/new","User\NewsController@index")->name("new");
  Route::get("/new_detail/{id?}","User\NewsController@new_detail")->name("new_detail");

  //INTRODUCE
  Route::get("/introduce","User\IntroduceController@index")->name("introduce");

  //SEND MAIL
  // Route::get("/send-mail","User\HomeController@send_mail");

  // LOGIN FACEBOOK
  Route::get('/login-facebook','Auth\AuthController@login_facebook');
  Route::get('/facebook/callback','Auth\AuthController@callback_facebook');

  // LOGIN GOOGLE
  Route::get('/login-google','Auth\AuthController@login_google');
  Route::get('/google/callback','Auth\AuthController@callback_google');
  

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  if(App::environment('production')){
    URL::forceScheme('https');
  }

resources/views/admin/statistic/comment_count.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Thống kê sản phẩm đánh giá nổi bật</p>
<!-- <div class="right__search">
    <form role="form" action="/search_product" method="get">
        @csrf
        <input type="search" class="search" name="txtSearch" id="" placeholder="Tìm kiếm" >
        <input type="submit" class="button" value="Search">
    </form>
</div>   -->
<?php
    use Illuminate\Support\Facades\Session;
    $message = Session::get('message');
    if($message){
        echo '<span style="color: red">'.$message.'</span>';
        Session::put('message',null);
    }
?>
<div class="right__table">
    <div class="right__tableWrapper">
        @php 
            $tt = 1;
        @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Tên sản phẩm</th>
                    <th>Số lượng đánh giá</th>
                    <th>Hình ảnh</th>
                </tr>
            </thead>
            <tbody>
                @foreach($comment_count as $r)
                    <tr>
                        <td data-label="STT">{{ $tt++}}</td>
                        <td data-label="Tên sảm phẩm" style="text-align:left">{{$r->product->ProductName}}</td>
                        <td data-label="Số lượng đánh giá" >{{$r->amount}}</td>
                        <td data-label="Xem hình ảnh" class="right__iconTable">
                            <a  data-id ="{{ $r->product->id }}" href="{{ route('product.show', $r->product->id) }}"><img src="{{ asset('assets/icon-eye.svg') }}" alt=""></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div>
    {{$comment_count->links()}}
</div>
@endsection

resources/views/admin/statistic/list_order_month.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Danh sách đơn hàng tháng {{ $month }}/{{ $year }}</p>
 
<?php
    use Illuminate\Support\Facades\Session;
    $message = Session::get('message');
    if($message){
        echo '<span style="color: red">'.$message.'</span>';
        Session::put('message',null);
    }
?>   
  <p style="font-size: 18px;">Tổng doanh thu tháng {{ $month }}/{{ $year }}: 
        <span style="color: red; font-weight: bold;">{{ number_format($order_total_year).' '.'đ' }} </span> 
    </p>
    <p style="font-size: 18px;">Tổng đơn hàng tháng {{ $month }}/{{ $year }}: 
        <span style="color: red; font-weight: bold;">{{ number_format($order_qty_year) }} </span> 
    </p>
<div class="right__table">
    <div class="right__tableWrapper">
    @php
        $tt = 1;
    @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã đơn hàng</th>
                    <th>Tên khách hàng</th>
                    <th>Ngày đặt</th>
                    <th>Số điện thoại nhận</th>
                    <th>Địa chỉ nhận</th>
                    <th>Tổng tiền (VNĐ)</th>
                    <th>Ghi chú</th>
                    <th>Trạng thái</th>
                    <th>In hóa đơn</th>
                    <th>Xem</th>
                    <th>Sửa</th>
                    <th>Xoá</th>
                </tr>
            </thead>
    
            <tbody>
                @foreach($order_list as  $r)
                    <tr>
                        <td>{{ $tt++ }}</td>
                        <td data-label="Mã đơn hàng">{{$r->id}}</td>
                        <td data-label="Tên khách hàng" style="text-align:left">{{ $r->customer->CustomerName }}</td>
                        <td data-label="Ngày đặt">{{ \Carbon\Carbon::parse($r->OrderDate)->format('d/m/Y') }}</td>
                        <td data-label="Số điện thoại nhận">{{ $r->ShipPhone }}</td>
                        <td data-label="Địa chỉ nhận" style="text-align:left">{{ $r->ShipAddress }}</td>
                        <td data-label="Tổng tiền(đ)" style="color:red; font-weight:bold; text-align:right">{{ number_format($r->total ) }}</td>
                        <td data-label="Ghi chú" style="text-align:left">{{ $r->Note }}</td>
                        <td data-label="Trạng thái">
                            @if( $r->Status == 0)
                                 <a href="#" class="label label-warning">Chờ xử lý</a>
                            @else
                                <a href="#" class="label-success label">Đã xử lý</a>
                            @endif
                        </td>
                        <td>
                             <a target="_blank" href="{{ route('print_order', $r->id) }}" class="label-info label">In hóa đơn</a>
                        </td>
                        <td data-label="Xem" class="right__iconTable">
                              <a  data-id ="{{ $r->id }}" href="{{ route('order.show', $r->id) }}"><img src="{{ asset('assets/icon-eye.svg') }}" alt=""></a>
                        </td>
                        <td data-label="Sửa" class="right__iconTable"><a href="{{ route('order.edit', $r->id) }}"><img src="{{asset('assets/icon-edit.svg')}}" alt=""></a></td>
                        <td data-label="Xoá" class="right__iconTable">
                            <form role="form" action="{{ route('order.destroy', $r->id) }}" method="post">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <button  type="submit" onclick="return confirm('Bạn có chắc chắn muốn xóa không?')"><img src="{{ asset('assets/icon-trash.svg') }}" alt=""></button>   
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div>
    {{ $order_list->links() }}
</div>


@endsection

resources/views/admin/statistic/order_count.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Thống kê số lượng đơn hàng hàng tháng</p>
<div class="container">
    <form action="" id="form_count" method="get">
        <div class="form-group">
            <label for="">Năm</label>
            <select class="count form-control form-control-sm" name="year">
              <option {{ Request::get('year') == "2021" || !Request::get('year') ? "selected='selected'" : "" }} value="2021" selected>2021</option>
              <option {{ Request::get('year') == "2022" ? "selected='selected'" : "" }} value="2022">2022</option>
              <option {{ Request::get('year') == "2023" ? "selected='selected'" : "" }} value="2023">2023</option>
              <option {{ Request::get('year') == "2024" ? "selected='selected'" : "" }} value="2024">2024</option>
              <option {{ Request::get('year') == "2025" ? "selected='selected'" : "" }} value="2025">2025</option>
              <option {{ Request::get('year') == "2026" ? "selected='selected'" : "" }} value="2026">2026</option>
              <option {{ Request::get('year') == "2027" ? "selected='selected'" : "" }} value="2027">2027</option>
              <option {{ Request::get('year') == "2028" ? "selected='selected'" : "" }} value="2028">2028</option>
              <option {{ Request::get('year') == "2029" ? "selected='selected'" : "" }} value="2029">2029</option>
              <option {{ Request::get('year') == "2030" ? "selected='selected'" : "" }} value="2030">2030</option>
            </select>
          </div>
    </form>
    <p style="font-size: 18px;">Tổng số đơn hàng năm {{ $year }}: 
        <span style="font-weight: bold;">{{ number_format($order_quantity_year)}} </span> 
    </p>
    <div class="row">
        @foreach($list_count as $value)
        <div class="col-sm-3">
            <div class="right__cards statistic">
                <a class="right__card" href="/statistic/order_list/{{$value['month']}}/{{ $year }}">
                    <div class="right__cardTitle">Tháng {{$value['month']}}</div>
                    <div class="right__cardNumber">{{ number_format($value['order_count'])}} </div>
                    <div class="right__cardDesc">Xem Chi Tiết <img src="{{asset('assets/arrow-right.svg')}}" alt=""></div>
                </a>
            </div>
        </div>
        
        @endforeach
    </div>
</div>
@endsection

resources/views/admin/statistic/order_highlight.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Thống kê đơn hàng nổi bật</p>

<form action="" id="form_hight" method="get">
        <div class="form-group">
            <label for="">Nổi bật về</label>
            <select class="hight form-control form-control-sm" name="hight">
              <option {{ Request::get('hight') == "qty" || !Request::get('hight') ? "selected='selected'" : "" }} value="qty" selected>Số lượng đơn hàng</option>
              <option {{ Request::get('hight') == "total" ? "selected='selected'" : "" }} value="total">Tổng tiền đặt</option>
            </select>
          </div>
    </form>
<div class="right__table mt-5">
    <div class="right__tableWrapper">
        @php
        $tt = 1;
        @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã khách hàng</th>
                    <th>Tên khách hàng</th>
                    <th>Địa chỉ</th>
                    <th>Số điện thoại</th>
                    <th>Tổng đơn đặt hàng</th>
                    <th>Tổng tiền đặt(VNĐ)</th>
                </tr>
            </thead>
            
            <tbody>
                @foreach($order_highlight  as  $r)
                <tr>
                    <td data-label="STT">{{ $tt++ }}</td>
                    <td data-label="Mã khách hàng">{{$r->customer->id}}</td>
                    <td data-label="Tên khách hàng" style="text-align:left">{{ $r->customer->CustomerName }}</td>
                    <td data-label="Địa chỉ"  style="text-align:left">{{ $r->customer->Address }}</td>
                    <td data-label="Số điện thoại">{{ $r->customer->Phone }}</td>
                    <td data-label="Tổng đơn hàng">{{ $r->amount }}</td>
                    <td data-label="Tổng tiền đặt(đ)" style="color:red; font-weight:bold; text-align:right">{{ number_format($r->sum_total ) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div>
    {{$order_highlight->links()}}
</div>
@endsection

resources/views/admin/statistic/order_pay.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Thống kê đơn hàng</p>
<div class="container">
    <div class="row">
        <div class="right__cards">
            <a class="right__card" href="">
                <div class="right__cardTitle">Tổng doanh thu <p>(đã + chờ xử lý)</p></div>
                <div class="right__cardNumber">{{ number_format($order_total) }} đ</div>
                <div class="right__cardDesc">Xem Chi Tiết <img src="{{asset('assets/arrow-right.svg')}}" alt=""></div>
            </a>
            <a class="right__card" href="{{ route('getOrderDone') }}">
                <div class="right__cardTitle">Tổng doanh thu (đã xử lý)</div>
                <div class="right__cardNumber">{{ number_format($order_total_done) }} đ</div>
                <div class="right__cardDesc">Xem Chi Tiết <img src="{{asset('assets/arrow-right.svg')}}" alt=""></div>
            </a>
            <a class="right__card" href="{{ route('getOrderWait') }}">
                <div class="right__cardTitle">Tổng doanh thu (chờ xử lý)</div>
                <div class="right__cardNumber">{{ number_format($order_total_wait) }} đ</div>
                <div class="right__cardDesc">Xem Chi Tiết <img src="{{asset('assets/arrow-right.svg')}}" alt=""></div>
            </a>
            <a class="right__card" href="">
                <div class="right__cardTitle">Doanh thu theo ngày tháng <p>(đã xử lý)</p></div>
                <div class="right__cardNumber">{{ number_format($order_total_date) }} đ</div>
                <div class="right__cardDesc">Xem Chi Tiết <img src="{{asset('assets/arrow-right.svg')}}" alt=""></div>
            </a>
        </div>
        <div class="col-md-6 left_date">
            <form role="form" action="" method="get">
                @csrf
                <div class="form-group">
                    <label for="">Từ <span class="time" > {{ \Carbon\Carbon::parse($date_from)->format('d/m/Y') }}</span></label>
                    <input type="date" name="date_from" value="" class="form-control @error('date_from') is-invalid @enderror"  value="{{ old('date_from') }}" required autocomplete="date_from" autofocus id="">
                    @error('date_from')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">đến <span class="time">{{ \Carbon\Carbon::parse($date_to)->format('d/m/Y') }}</span></label>
                    <input type="date" name="date_to" value="" class="form-control @error('date_to') is-invalid @enderror"  value="{{ old('date_to') }}" required autocomplete="date_to" autofocus  id="">
                    @error('date_to')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>
                <input type="submit" class="btn btn-success" value="THỐNG KÊ">
            </form>
        </div> 
    </div>
</div>


<?php
use Illuminate\Support\Facades\Session;
$message = Session::get('message');
if($message){
    echo '<span style="color: red">'.$message.'</span>';
    Session::put('message',null);
}
?>   
<div class="right__table mt-5">
    <div class="right__tableWrapper">
        @php
        $tt = 1;
        @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã đơn hàng</th>
                    <th>Tên khách hàng</th>
                    <th>Ngày đặt</th>
                    <th>Số điện thoại nhận</th>
                    <th>Địa chỉ nhận</th>
                    <th>Tổng tiền (VNĐ)</th>
                    <th>Ghi chú</th>
                    <th>Trạng thái</th>
                    <th>In hóa đơn</th>
                    <th>Xem</th>
                    <th>Xoá</th>
                </tr>
            </thead>
            
            <tbody>
                @foreach($order_pay as  $r)
                <tr>
                    <td data-label="STT">{{ $tt++ }}</td>
                    <td data-label="Mã đơn hàng">{{$r->id}}</td>
                    <td data-label="Tên khách hàng" style="text-align:left">{{ $r->customer->CustomerName }}</td>
                    <td data-label="Ngày đặt">{{ \Carbon\Carbon::parse($r->OrderDate)->format('d/m/Y') }}</td>
                    <td data-label="Số điện thoại nhận">{{ $r->ShipPhone }}</td>
                    <td data-label="Địa chỉ nhận" style="text-align:left">{{ $r->ShipAddress }}</td>
                    <td data-label="Tổng tiền(đ)" style="color:red; font-weight:bold; text-align:right">{{ number_format($r->total ) }}</td>
                    <td data-label="Ghi chú" style="text-align:left">{{ $r->Note }}</td>
                    <td data-label="Trạng thái">
                        @if( $r->Status == 0)
                        <a href="#" class="label label-warning">Chờ xử lý</a>
                        @else
                        <a href="#" class="label-success label">Đã xử lý</a>
                        @endif
                    </td>
                    <td>
                        <a target="_blank" href="{{ route('print_order', $r->id) }}" class="label-info label">In hóa đơn</a>
                    </td>
                    <td data-label="Xem" class="right__iconTable">
                        <a  data-id ="{{ $r->id }}" href="{{ route('order.show', $r->id) }}"><img src="{{ asset('assets/icon-eye.svg') }}" alt=""></a>
                    </td>
                    <td data-label="Xoá" class="right__iconTable">
                        <form role="form" action="{{ route('order.destroy', $r->id) }}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button  type="submit" onclick="return confirm('Bạn có chắc chắn muốn xóa không?')"><img src="{{ asset('assets/icon-trash.svg') }}" alt=""></button>   
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <a href="{{ route('order.index') }}" class="right__tableMore"><p>Xem tất cả các đơn đặt hàng</p> <img src="{{asset('assets/arrow-right-black.svg')}}" alt=""></a>
</div>

@endsection

resources/views/admin/statistic/product_pay.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Thống kê sản phẩm bán chạy nhất</p>
<!-- <div class="right__search">
    <form role="form" action="/search_product" method="get">
        @csrf
        <input type="search" class="search" name="txtSearch" id="" placeholder="Tìm kiếm" >
        <input type="submit" class="button" value="Search">
    </form>
</div>   -->
<?php
    use Illuminate\Support\Facades\Session;
    $message = Session::get('message');
    if($message){
        echo '<span style="color: red">'.$message.'</span>';
        Session::put('message',null);
    }
?>
<div class="right__table">
    <div class="right__tableWrapper">
        @php 
            $tt = 1;
        @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã sản phẩm</th>
                    <th>Tên sản phẩm</th>
                    <th>Tên loại</th>
                    <th>Số lượng được đặt</th>
                    <th>Đơn giá (VNĐ)</th>
                    <th>Hình ảnh</th>
                </tr>
            </thead>
            <tbody>
                @foreach($product_pay as $r)
                    <tr>
                        <td data-label="STT">{{ $tt++}}</td>
                        <td data-label="Mã sản phẩm">{{$r->product->id}}</td>
                        <td data-label="Tiêu đề" style="text-align:left">{{$r->product->ProductName}}</td>
                        <td data-label="Tên loại" style="text-align:left">{{ $r->product->category->CategoryName }}</td>
                        <td data-label="Số lượng được đặt" >{{ $r->amount }}</td>
                        <td data-label="Đơn giá(đ)" style="color:red; font-weight:bold; text-align:right"> {{ number_format($r->product->Price) }}</td>
                        <td data-label="Xem hình ảnh" class="right__iconTable">
                              <a  data-id ="{{ $r->product->id }}" href="{{ route('product.show', $r->product->id) }}"><img src="{{ asset('assets/icon-eye.svg') }}" alt=""></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div>
    {{$product_pay->links()}}
</div>
@endsection