routes/web.php
<?php
use \Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
    //     return view('welcome');
    // });
    
    
    //----------------------------------------------     ADMIN PAGE    ----------------------------------------------------//
    
    Auth::routes();
    // LOGOUT
    // Route::middleware(['role'])->group(function () {
        
        // });
        
  Route::get('login_auth', 'Auth\AuthController@getFormLogin')->name('login_auth');
  Route::post('login_auth', 'Auth\AuthController@submitLogin')->name('login_auth');
  Route::get('logout', 'Auth\AuthController@logout')->name('logout');

  Route::group(['middleware' => ['auth','role']], function () {
      Route::get('/admin/index', 'Admin\HomeController@index')->name('/admin/index');
      
      // CATEGORY
      Route::resource('/category', 'Admin\CategoryProductController');
      Route::get('/search_category', 'Admin\CategoryProductController@search')->name('search_category');
      
      // PRODUCT
      Route::resource('/product', 'Admin\ProductsController');
      Route::get('/search_product', 'Admin\ProductsController@search')->name('search_product');
      Route::get('export_products', 'Admin\ProductsController@export')->name('export_products');
      Route::post('import_products', 'Admin\ProductsController@import')->name('import_products');
      
      // CUSTOMER
      Route::resource('/customer', 'Admin\CustomersController');
      Route::get('/search_customer', 'Admin\CustomersController@search')->name('search_customer');
      
      // USERS
      Route::resource('user', 'Admin\UsersController');
      Route::get('/search_user', 'Admin\UsersController@search')->name('search_user');
      
      // ROLES
      Route::resource('role', 'Admin\RolesController');
      Route::get('/search_role', 'Admin\RolesController@search')->name('search_role');
      
      // PICTURES
      Route::resource('picture', 'Admin\PictureController');
      Route::get('/search_picture', 'Admin\PictureController@search')->name('search_picture');
      
      //ORDER
      Route::resource('order', "Admin\OrdersController");
      Route::get('/search_order', 'Admin\OrdersController@search');
      Route::get('/getOrderCurrent', 'Admin\OrdersController@getOrderCurrent')->name('getOrderCurrent');
      Route::get('/getOrderDone', 'Admin\OrdersController@getOrderDone')->name('getOrderDone');
      Route::get('/getOrderWait', 'Admin\OrdersController@getOrderWait')->name('getOrderWait');
      Route::get('/print_order/{checkout_code}', "Admin\OrdersController@print_order")->name("print_order");
      
      
      //CONTACT
      Route::resource('contact_admin', 'Admin\ContactController');
      Route::get('/search_contact', 'Admin\ContactController@search')->name('search_contact');
      
      //STATISTICS
      Route::get('/statistic/index', 'Admin\StatisticsController@index')->name('/statistic/index');
      Route::get('/statistic/order_pay', 'Admin\StatisticsController@getOrder')->name("/statistic/order_pay");
      Route::get('/statistic/comment_count', 'Admin\StatisticsController@getComment')->name("/statistic/comment_count");
      Route::get('/statistic/order_highlight', 'Admin\StatisticsController@getOrderHighlight')->name("/statistic/order_highlight");
      Route::get('/statistic/order_time', 'Admin\StatisticsController@getOrderTime')->name("/statistic/order_time");
      Route::get('/statistic/order_quarter', 'Admin\StatisticsController@getOrderQuarter')->name("/statistic/order_quarter");
      Route::get('/statistic/order_count', 'Admin\StatisticsController@getOrderCount')->name("/statistic/order_count");
      Route::get('/statistic/order_list/{month}/{year}', 'Admin\StatisticsController@getListOrderTime')->name("/statistic/order_list");


      // THỐNG KÊ DẠNG BIỂU DỒ
      Route::get('/statistic/chart/revenue', 'Admin\StatisticsController@Revenue')->name('revenue');
      Route::post('/statistic/chart/filter_by_date', 'Admin\StatisticsController@filter_by_date')->name('filter_by_date');
      Route::post('/statistic/chart/filter_by_month_year', 'Admin\StatisticsController@filter_by_month_year')->name('filter_by_month_year');
      Route::post('/statistic/chart/filter_by_year', 'Admin\StatisticsController@filter_by_year')->name('filter_by_year');
      Route::post('/statistic/chart/get_revenue_filter_date', 'Admin\StatisticsController@getRevenueFilterDate')->name('get_revenue_filter_date');
      Route::post('/statistic/chart/get_revenue_today', 'Admin\StatisticsController@getRevenueToday')->name('get_revenue_today');
      Route::post('/statistic/chart/filter_by_quater', 'Admin\StatisticsController@filter_by_quater')->name('filter_by_quater');
      
      
      // COMMENT
      Route::resource('comment', 'Admin\CommentsController');
      Route::get('/search_comment', 'Admin\CommentsController@search')->name('search_comment');
      
      // DISCOUNT
      Route::resource('discount', 'Admin\DiscountController');
      Route::get('/search_discount', 'Admin\DiscountController@search')->name('search_discount');
      
      //NEWS
      Route::resource('news', 'Admin\NewsController');
      Route::get('/search_new', 'Admin\NewsController@search')->name('search_new');
      
      //Excel
      Route::get('export', 'MyController@export')->name('export');
      Route::get('importExportView', 'MyController@importExportView');
      Route::post('import', 'MyController@import')->name('import');
      
    
  });
    // LANGUAGE
    Route::get('/language/{language}','Admin\LanguageController@index')->name('language.index');
  // Route::get('/admin/index', 'Admin\HomeController@index')->name('/admin/index')->middleware(['auth','role']);


  //----------------------------------------------     USER PAGE    ----------------------------------------------------//

  Route::get('/', 'User\HomeController@index')->name('index');
  Route::get('/search', 'User\HomeController@index')->name("search");
  Route::get('/listproduct/{id?}', 'User\ProductController@index')->name('listproduct');
  Route::get('/product_detail/{id?}', 'User\ProductDetailController@index')->name('product_detail');

  // SHOPPING CART
  Route::resource('cart', "User\CartController");
  Route::get('addcart/{id?}', "User\CartController@addCart")->name("addcart");
  Route::put('updateAll', "User\CartController@updateAll")->name("updateAll");

  //CHECK OUT

  
Route::get('get-district-list/{province_id}','User\CheckoutController@getDistrictByProvince');
Route::get('get-ward-list/{district_id}','User\CheckoutController@getWardByDistrict');

  Route::get('get_login_order', "User\CheckoutController@get_login_order")->name("get_login_order");
  Route::post('login_order', "User\CheckoutController@login_order")->name("login_order");
  Route::get('logout_checkout', "User\CheckoutController@logout_checkout")->name("logout_checkout");

  // Route::get('history', "User\CheckoutController@history")->middleware(['auth','history:user'])->name("history");
  Route::get('history', "User\CheckoutController@history")->name("history");
  Route::get('history_order_detail/{id?}', "User\CheckoutController@history_order_detail")->name("history_order_detail");

  Route::get('checkout', "User\CheckoutController@getFormPay")->name("checkout");
  Route::get('checkout_success', "User\CheckoutController@success")->name("checkout_success");
  Route::post('checkout', "User\CheckoutController@postFormPay")->name("checkout");

  Route::post('vnpay_payment', "User\CheckoutController@vnpay_payment")->name("vnpay_payment");


  // CONTACT
  Route::get('/contact', "User\ContactController@index")->name("contact");
  Route::post('/contact', "User\ContactController@saveContact")->name("contact");

  // COMMENT 
  Route::post('/comment/{id?}', "User\ProductDetailController@saveComment")->name("comment");


  // NEWS
  Route::get("/new","User\NewsController@index")->name("new");
  Route::get("/new_detail/{id?}","User\NewsController@new_detail")->name("new_detail");

  //INTRODUCE
  Route::get("/introduce","User\IntroduceController@index")->name("introduce");

  //SEND MAIL
  // Route::get("/send-mail","User\HomeController@send_mail");

  // LOGIN FACEBOOK
  Route::get('/login-facebook','Auth\AuthController@login_facebook');
  Route::get('/facebook/callback','Auth\AuthController@callback_facebook');

  // LOGIN GOOGLE
  Route::get('/login-google','Auth\AuthController@login_google');
  Route::get('/google/callback','Auth\AuthController@callback_google');
  

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  if(App::environment('production')){
    URL::forceScheme('https');
  }

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\CategoryProducts;
use App\Models\Products;
use App\Models\Picture;
use App\Http\Requests\ProductRequest;
// use Auth;
use App\Exports\ProductsExport;
use App\Imports\ProductsImport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Auth;
use CloudinaryLabs\CloudinaryLaravel\Facades\Cloudinary;


class ProductsController extends Controller
{
    public function AuthLogin()
    {
        $admin_id = Auth::id();
        if ($admin_id) {
            return redirect()->route('/admin/index');
        }else {
            return redirect()->route('login');
        }
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $this->AuthLogin();
        $db = Products::orderBy("id","desc")->paginate(10);
        return view('admin.product.product', compact('db'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $db = CategoryProducts::all();
        // $db = CategoryProducts::where("CategoryName");
        return view("admin.product.add_product", ['db'=>$db]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        //
        if($request->hasfile('fileImg')){
            $file = $request->file('fileImg');
            $obj = Cloudinary::upload($file->getRealPath(), ['folder' => 'products']);
            $public_id = $obj->getPublicId();
            $url = $obj->getSecurePath();
        }
        else {
            return $request;
        }

        $product_id = Products::insertGetId([
            'ProductName' => $request->txtName,
            'Cate_Id' => $request->txtCate,
            'Description' => $request->txtDes,
            'Picture' => $url,
            'Price' => $request->txtprice,
            'Quantity' => $request->nQuantity,
            'Status' => $request->sl_stt,
            'public_id' => $public_id,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        $get_image = $request->file('images');
        if($get_image){
            foreach ($get_image as $image) {
                $uploadedFile = Cloudinary::upload($image->getRealPath(), [
                    'folder' => "products"
                ]);
                $image_public_id = $uploadedFile->getPublicId();
                $uploadedFileUrl = $uploadedFile->getSecurePath();
                if ($product_id) {
                    Picture::insert([
                        'picture' => $uploadedFileUrl,
                        'status' => 1,
                        'ProductId' => $product_id,
                        'public_id' => $image_public_id,
                        'created_at' => now(),
                        'updated_at' => now()
                    ]);
                }

            }
        }
        return redirect()->route('product.index')->with('message', 'Thêm sản phẩm thành công');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $pictures = Products::find($id)->pictures;
        return view("admin.product.show_picture", compact("pictures"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id=null)
    {
        //
        if ($id==null) {
            return redirect()->route("product.index");
        }
        else {
            $db = Products::find($id);
            $categories = CategoryProducts::all();
            $pictures = Products::find($id)->pictures;
            return view("admin.product.edit_product",compact("db","categories","pictures"));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        //
        $db = Products::find($id);
        $db->ProductName = $request->input('txtName');
        $db->Cate_Id = $request->input('txtCate');
        $db->Description = $request->input('txtDes');
        $public_id = $db->public_id;

       if(!$request->hasfile('fileImg')){
          $db->Picture = $request->input("image");
       }
       else {
            if($request->hasfile('fileImg')){
                Cloudinary::destroy($public_id);
                $file = $request->file('fileImg');
                $obj = Cloudinary::upload($file->getRealPath(), ['folder' => 'products']);
                $public_id = $obj->getPublicId();
                $url = $obj->getSecurePath();
                $db->Picture = $url;
                $db->public_id = $public_id;
            }
            else {
                $db->Picture = "";
                $db->public_id = "";
            }
       }


       $get_image = $request->file('images');
       if($get_image){
            $pictures = Picture::where("ProductId", $id)->get();
            foreach ($pictures as $picture) {
                Cloudinary::destroy($picture->public_id);
            }
            Picture::where("ProductId", $id)->delete();
            foreach ($get_image as $image) {
               $objImageDetail = Cloudinary::upload($image->getRealPath(), ['folder' => 'products']);
               $image_public_id = $objImageDetail->getPublicId();
               $image_url = $objImageDetail->getSecurePath();
               if ($id) {
                    Picture::insert([
                       'picture' => $image_url,
                       'status' => 1,
                       'ProductId' => $id,
                       "public_id" => $image_public_id,
                       'created_at' => now(),
                       'updated_at' => now()
                   ]);
               }
           }
        }
        $db->Price = $request->input('txtprice');
        $db->Quantity = $request->input('nQuantity');
        $db->Status = $request->input('sl_stt');
        $db->save();
        return redirect()->route("product.index", [$id])->with('message', 'Cập nhật sản phẩm thành công');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $db = Products::findOrFail($id);
        Cloudinary::destroy($db->public_id);
        $pictures = Picture::where("ProductId", $id)->get();
        foreach ($pictures as $picture) {
            Cloudinary::destroy($picture->public_id);
        }
        $db->delete();
        return redirect()->route("product.index")->with('message', 'Xóa sản phẩm thành công');
    }


    public function search(Request $request)
    {
        //
        $text = $request->input("txtSearch");
        if ($text == "") {
            $db = Products::paginate(10);
        }
        else {
            $db = Products::join('category_products','products.Cate_id','=','category_products.id')
                           ->select('products.*')
                           ->where('products.ProductName','LIKE','%'.$text.'%')
                           ->orWhere('products.id','LIKE','%'.$text.'%')
                           ->orWhere('products.Price','LIKE','%'.$text.'%')
                           ->orWhere('category_products.CategoryName','LIKE','%'.$text.'%')->paginate(1000);
        }
        return view('admin.product.product', ['db'=>$db]);
    }


    /**
    * @return \Illuminate\Support\Collection
    */
    public function export()
    {
        return Excel::download(new ProductsExport, 'products.xlsx');
    }


    /**
    * @return \Illuminate\Support\Collection
    */
    public function import()
    {
        Excel::import(new ProductsImport,request()->file('file'));
        return back();
    }
}

resources/views/admin/product/add_product.blade.php
@extends('layouts.admin')
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Thêm sản phẩm</p>
<div class="right__formWrapper">
    <form role="form" action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="right__inputWrapper">
            <label for="title">Tên sách</label>
            <input type="text" name="txtName" class="form-control @error('txtName') is-invalid @enderror"  placeholder="Tên sách" value="{{ old('txtName') }}" required autocomplete="txtName" autofocus>
            @error('txtName')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div class="right__inputWrapper">
            <label for="p_category">Loại sách</label>
            <select name="txtCate" class="form-control form-control-sm">
                @foreach($db as $r)
                    <option value="{{ $r->id }}">{{ $r->CategoryName }}</option>
                @endforeach
            </select>
        </div>
        <div class="right__inputWrapper">
            <label for="desc">Mô tả</label>
            <textarea name="txtDes" id="ckeditor2" cols="30" rows="10" placeholder="Mô tả" class="form-control @error('txtDes') is-invalid @enderror" value="{{ old('txtDes') }}" required autocomplete="txtDes" autofocus></textarea>
            @error('txtDes')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div class="right__inputWrapper">
            <label for="image">Hình ảnh 1</label>
            <input type="file" name="fileImg" class="form-control" required>
        </div>
        <div class="right__inputWrapper">
            <label for="images">Hình ảnh liên quan</label>
            <input type="file" name="images[]" class="form-control" required multiple="multiple">
            
        </div>
        <div class="right__inputWrapper">
            <label for="price">Đơn giá</label>
            <input type="number" name="txtprice" class="form-control @error('txtprice') is-invalid @enderror"  placeholder="Đơn giá" value="{{ old('txtprice') }}" required min=0 autocomplete="txtprice" autofocus>
            @error('txtprice')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div class="right__inputWrapper">
            <label for="quantity">Số lượng tồn</label>
            <input type="number" name="nQuantity" class="form-control @error('nQuantity') is-invalid @enderror"  placeholder="Số lượng" value="{{ old('nQuantity') }}" min=1 required autocomplete="nQuantity" autofocus>
            @error('nQuantity')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div class="right__inputWrapper">
            <label for="p_category">Trạng thái</label>
            <select name="sl_stt" class="form-control form-control-sm">
                <option value="1">Hiển thị</option>
                <option value="0">Ẩn</option>
            </select>
        </div>
        <button class="btn btn-info" type="submit">Thêm</button>
    </form>
</div>
@endsection

resources/views/admin/product/product.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Danh sách sản phẩm</p>
<div class="right__search">
    <form role="form" action="/search_product" method="get">
        @csrf
        <input style="width: 250px;" type="search" class="search" name="txtSearch" id="" placeholder="Tìm theo mã sách, tên sách, tên loại, giá" title="Tìm theo mã sách, tên sách, tên loại, giá">
        <input type="submit" class="button" value="Tìm kiếm" title="Tìm theo mã sách, tên sách, tên loại, giá">
    </form>
</div>  
<?php
    use Illuminate\Support\Facades\Session;
    $message = Session::get('message');
    if($message){
        echo '<span style="color: red">'.$message.'</span>';
        Session::put('message',null);
    }
?>

<div class="right__table">
    <div class="right__tableWrapper">
        @php 
            $tt = 1;
        @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã sách</th>
                    <th>Tên sách</th>
                    <th>Tên loại</th>
                    <th>Số lượng tồn</th>
                    <th>Đơn giá (VNĐ)</th>
                    <th>Hình ảnh</th>
                    <th>Hiển thị</th>
                    <th>Sửa</th>
                    <th>Xoá</th>
                </tr>
            </thead>
            <tbody>
                @foreach($db as $r)
                    <tr>
                        <td data-label="STT">{{ $tt++}}</td>
                        <td data-label="Mã sách">{{$r->id}}</td>
                        <td data-label="Tiêu đề" style="text-align:left">{{$r->ProductName}}</td>
                        <td data-label="Tên loại" style="text-align:left">{{ $r->category->CategoryName }}</td>
                        <td data-label="Số lượng tồn">{{ $r->Quantity }}</td>
                        <td data-label="Đơn giá(đ)" style="color:red; font-weight:bold; text-align:right"> {{ number_format($r->Price) }}</td>
                        <td data-label="Xem hình ảnh" class="right__iconTable">
                              <a  data-id ="{{ $r->id }}" href="{{ route('product.show', $r->id) }}"><img src="{{ asset('assets/icon-eye.svg') }}" alt=""></a>
                        </td>
                        <td data-label="Hiển thị">
                            <!-- <input type="checkbox" name="cbtt" value="{{ $r->Status }}" {{ $r->Status==0?'':'checked'}}> -->
                            @if( $r->Status == 0)
                                 <a href="#" class="label label-warning">Ẩn</a>
                            @else
                                <a href="#" class="label-success label">Hiển Thị</a>
                            @endif
                         </td>
                        <td data-label="Sửa" class="right__iconTable"><a href="{{ route('product.edit', $r->id) }}"><img src="{{asset('assets/icon-edit.svg')}}" alt=""></a></td>
                        <td data-label="Xoá" class="right__iconTable">
                            <form role="form" action="{{ route('product.destroy', $r->id) }}" method="post">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <button  type="submit" onclick="return confirm('Bạn có chắc chắn muốn xóa không?')"><img src="{{ asset('assets/icon-trash.svg') }}" alt=""></button>   
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div>
    {{$db->links()}}
</div>

<div class="card bg-light mt-3">
    <div class="card-header">
        Nhập và xuất ra Excel
    </div>
    <div class="card-body">
        <form action="{{ route('import_products') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="file" name="file" class="form-control">
            <br>
            <button class="btn btn-success">Nhập dữ liệu sản phẩm</button>
            <a class="btn btn-warning" href="{{ route('export_products') }}">Xuất dữ liệu sản phẩm</a>
        </form>
    </div>
</div>

@endsection

resources/views/admin/product/show_picture.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Xem hình ảnh</p>
<!-- <div class="right__search">
    <form role="form" action="/search_category" method="get">
       @csrf
        <input type="search" class="search" class="form-control"  name="txtSearch" id="" placeholder="Tìm kiếm" >
        <input type="submit" class="button" value="Search">
    </form>
</div>    -->
 
<div class="right__table">
    <div class="right__tableWrapper">
    @php
        $tt = 0;
    @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã ảnh</th>
                    <th>Tên sách</th>
                    <th>Hình ảnh</th>
                    <th>Sửa</th>
                    <th>Xoá</th>
                </tr>
            </thead>
    
            <tbody>
                @foreach($pictures as $r)
                    <tr>
                        <td data-label="STT">{{ $tt++ }}</td>
                        <td data-label="Mã ảnh">{{$r->id}}</td>
                        <td data-label="Tên sách">{{$r->product->ProductName}}</td>
                        <td data-label="Hình ảnh"> <img src="{{$r->picture}}" alt="" > </td>
                        <td data-label="Sửa" class="right__iconTable"><a href="{{ route('picture.edit', $r->id) }}"><img src="{{asset('assets/icon-edit.svg')}}" alt=""></a></td>
                        <td data-label="Xoá" class="right__iconTable">
                            <form role="form" action="{{ route('picture.destroy', $r->id) }}" method="post">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <button  type="submit" onclick="return confirm('Bạn có chắc chắn muốn xóa không?')"><img src="{{ asset('assets/icon-trash.svg') }}" alt=""></button>   
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div>
  
</div>
@endsection