routes/web.php
<?php
use \Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
    //     return view('welcome');
    // });
    
    
    //----------------------------------------------     ADMIN PAGE    ----------------------------------------------------//
    
    Auth::routes();
    // LOGOUT
    // Route::middleware(['role'])->group(function () {
        
        // });
        
  Route::get('login_auth', 'Auth\AuthController@getFormLogin')->name('login_auth');
  Route::post('login_auth', 'Auth\AuthController@submitLogin')->name('login_auth');
  Route::get('logout', 'Auth\AuthController@logout')->name('logout');

  Route::group(['middleware' => ['auth','role']], function () {
      Route::get('/admin/index', 'Admin\HomeController@index')->name('/admin/index');
      
      // CATEGORY
      Route::resource('/category', 'Admin\CategoryProductController');
      Route::get('/search_category', 'Admin\CategoryProductController@search')->name('search_category');
      
      // PRODUCT
      Route::resource('/product', 'Admin\ProductsController');
      Route::get('/search_product', 'Admin\ProductsController@search')->name('search_product');
      Route::get('export_products', 'Admin\ProductsController@export')->name('export_products');
      Route::post('import_products', 'Admin\ProductsController@import')->name('import_products');
      
      // CUSTOMER
      Route::resource('/customer', 'Admin\CustomersController');
      Route::get('/search_customer', 'Admin\CustomersController@search')->name('search_customer');
      
      // USERS
      Route::resource('user', 'Admin\UsersController');
      Route::get('/search_user', 'Admin\UsersController@search')->name('search_user');
      
      // ROLES
      Route::resource('role', 'Admin\RolesController');
      Route::get('/search_role', 'Admin\RolesController@search')->name('search_role');
      
      // PICTURES
      Route::resource('picture', 'Admin\PictureController');
      Route::get('/search_picture', 'Admin\PictureController@search')->name('search_picture');
      
      //ORDER
      Route::resource('order', "Admin\OrdersController");
      Route::get('/search_order', 'Admin\OrdersController@search');
      Route::get('/getOrderCurrent', 'Admin\OrdersController@getOrderCurrent')->name('getOrderCurrent');
      Route::get('/getOrderDone', 'Admin\OrdersController@getOrderDone')->name('getOrderDone');
      Route::get('/getOrderWait', 'Admin\OrdersController@getOrderWait')->name('getOrderWait');
      Route::get('/print_order/{checkout_code}', "Admin\OrdersController@print_order")->name("print_order");
      
      
      //CONTACT
      Route::resource('contact_admin', 'Admin\ContactController');
      Route::get('/search_contact', 'Admin\ContactController@search')->name('search_contact');
      
      //STATISTICS
      Route::get('/statistic/index', 'Admin\StatisticsController@index')->name('/statistic/index');
      Route::get('/statistic/order_pay', 'Admin\StatisticsController@getOrder')->name("/statistic/order_pay");
      Route::get('/statistic/comment_count', 'Admin\StatisticsController@getComment')->name("/statistic/comment_count");
      Route::get('/statistic/order_highlight', 'Admin\StatisticsController@getOrderHighlight')->name("/statistic/order_highlight");
      Route::get('/statistic/order_time', 'Admin\StatisticsController@getOrderTime')->name("/statistic/order_time");
      Route::get('/statistic/order_quarter', 'Admin\StatisticsController@getOrderQuarter')->name("/statistic/order_quarter");
      Route::get('/statistic/order_count', 'Admin\StatisticsController@getOrderCount')->name("/statistic/order_count");
      Route::get('/statistic/order_list/{month}/{year}', 'Admin\StatisticsController@getListOrderTime')->name("/statistic/order_list");


      // THỐNG KÊ DẠNG BIỂU DỒ
      Route::get('/statistic/chart/revenue', 'Admin\StatisticsController@Revenue')->name('revenue');
      Route::post('/statistic/chart/filter_by_date', 'Admin\StatisticsController@filter_by_date')->name('filter_by_date');
      Route::post('/statistic/chart/filter_by_month_year', 'Admin\StatisticsController@filter_by_month_year')->name('filter_by_month_year');
      Route::post('/statistic/chart/filter_by_year', 'Admin\StatisticsController@filter_by_year')->name('filter_by_year');
      Route::post('/statistic/chart/get_revenue_filter_date', 'Admin\StatisticsController@getRevenueFilterDate')->name('get_revenue_filter_date');
      Route::post('/statistic/chart/get_revenue_today', 'Admin\StatisticsController@getRevenueToday')->name('get_revenue_today');
      Route::post('/statistic/chart/filter_by_quater', 'Admin\StatisticsController@filter_by_quater')->name('filter_by_quater');
      
      
      // COMMENT
      Route::resource('comment', 'Admin\CommentsController');
      Route::get('/search_comment', 'Admin\CommentsController@search')->name('search_comment');
      
      // DISCOUNT
      Route::resource('discount', 'Admin\DiscountController');
      Route::get('/search_discount', 'Admin\DiscountController@search')->name('search_discount');
      
      //NEWS
      Route::resource('news', 'Admin\NewsController');
      Route::get('/search_new', 'Admin\NewsController@search')->name('search_new');
      
      //Excel
      Route::get('export', 'MyController@export')->name('export');
      Route::get('importExportView', 'MyController@importExportView');
      Route::post('import', 'MyController@import')->name('import');
      
    
  });
    // LANGUAGE
    Route::get('/language/{language}','Admin\LanguageController@index')->name('language.index');
  // Route::get('/admin/index', 'Admin\HomeController@index')->name('/admin/index')->middleware(['auth','role']);


  //----------------------------------------------     USER PAGE    ----------------------------------------------------//

  Route::get('/', 'User\HomeController@index')->name('index');
  Route::get('/search', 'User\HomeController@index')->name("search");
  Route::get('/listproduct/{id?}', 'User\ProductController@index')->name('listproduct');
  Route::get('/product_detail/{id?}', 'User\ProductDetailController@index')->name('product_detail');

  // SHOPPING CART
  Route::resource('cart', "User\CartController");
  Route::get('addcart/{id?}', "User\CartController@addCart")->name("addcart");
  Route::put('updateAll', "User\CartController@updateAll")->name("updateAll");

  //CHECK OUT

  
Route::get('get-district-list/{province_id}','User\CheckoutController@getDistrictByProvince');
Route::get('get-ward-list/{district_id}','User\CheckoutController@getWardByDistrict');

  Route::get('get_login_order', "User\CheckoutController@get_login_order")->name("get_login_order");
  Route::post('login_order', "User\CheckoutController@login_order")->name("login_order");
  Route::get('logout_checkout', "User\CheckoutController@logout_checkout")->name("logout_checkout");

  // Route::get('history', "User\CheckoutController@history")->middleware(['auth','history:user'])->name("history");
  Route::get('history', "User\CheckoutController@history")->name("history");
  Route::get('history_order_detail/{id?}', "User\CheckoutController@history_order_detail")->name("history_order_detail");

  Route::get('checkout', "User\CheckoutController@getFormPay")->name("checkout");
  Route::get('checkout_success', "User\CheckoutController@success")->name("checkout_success");
  Route::post('checkout', "User\CheckoutController@postFormPay")->name("checkout");

  Route::post('vnpay_payment', "User\CheckoutController@vnpay_payment")->name("vnpay_payment");


  // CONTACT
  Route::get('/contact', "User\ContactController@index")->name("contact");
  Route::post('/contact', "User\ContactController@saveContact")->name("contact");

  // COMMENT 
  Route::post('/comment/{id?}', "User\ProductDetailController@saveComment")->name("comment");


  // NEWS
  Route::get("/new","User\NewsController@index")->name("new");
  Route::get("/new_detail/{id?}","User\NewsController@new_detail")->name("new_detail");

  //INTRODUCE
  Route::get("/introduce","User\IntroduceController@index")->name("introduce");

  //SEND MAIL
  // Route::get("/send-mail","User\HomeController@send_mail");

  // LOGIN FACEBOOK
  Route::get('/login-facebook','Auth\AuthController@login_facebook');
  Route::get('/facebook/callback','Auth\AuthController@callback_facebook');

  // LOGIN GOOGLE
  Route::get('/login-google','Auth\AuthController@login_google');
  Route::get('/google/callback','Auth\AuthController@callback_google');
  

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  Auth::routes();

  Route::get('/home', 'HomeController@index')->name('home');

  if(App::environment('production')){
    URL::forceScheme('https');
  }

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'password', 'email','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        
    ];
    public function role()
    {
        return $this->belongsTo('App\Models\Roles','role_id');
    }

   
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Models\Roles;
use Illuminate\Support\Facades\Hash;
use Auth;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $db = User::orderBy('id','DESC')->paginate(10);
        return view("admin.user.users", compact("db"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id=null)
    {
        //
        if ($id == null) {
            return redirect()->route("user.index");
        }
        else {
            $db = User::find($id);
            $role = Roles::all();
            return view("admin.user.edit_user",['db'=>$db,'role'=>$role]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $db = User::find($id);
        $db->username = $request->input('txtName');
        $db->password = Hash::make($request->input('txtpw')) ;
        $db->role_id = $request->input('sl_role');
        $db->status = $request->input('slstt');
        $db->save();
        return redirect()->route('user.index',[$id])->with("message","Cập nhật thành công");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $db = User::findOrFail($id);
        $db->delete();
        return redirect()->route("user.index")->with("Xóa thành công");
    }

    public function search(Request $request)
    {
        //
        $text = $request->input("txtSearch");
        if ($text == "") {
            $db = User::paginate(10);
        }
        else {
            $db = User::join('roles', 'users.role_id','=','roles.id')
                            ->select('users.*')
                            ->where('users.username','LIKE','%'.$text.'%')
                            ->orWhere('users.id','LIKE','%'.$text.'%')
                            ->orWhere('users.created_at','LIKE','%'.$text.'%')
                            ->orWhere('roles.name','LIKE','%'.$text.'%')
                            ->paginate(1000);
        }
        return view('admin.user.users', ['db'=>$db]);
    }
}

app/Http/Controllers/User/CartController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\CategoryProducts;
use App\Helpers;
use App\Models\Products;
use App\Models\OrderDetails;
use App\Models\Orders;
use App\Models\Discount;
use Cart;
use DB;
use Section;
// session_start();

class CartController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index(Request $request)
    {
        //
        $categories = CategoryProducts::all();
        $cart = Cart::content();
        // $product_pay = OrderDetails::groupBy('ProductId')       // PRODUCT PAY
        //             ->selectRaw('sum(Quantity) as amount, ProductId')
        //             ->orderBy('amount','desc')->limit(10)->get();
        // $product_pay = OrderDetails::orderBy('amount','desc')
        //             ->select(DB::raw('sum(Quantity) as amount, ProductId'))
        //             ->groupBy('ProductId')
        //             ->limit(10)->get();
        $product_pay = OrderDetails::orderBy('id', 'DESC')->limit(10)->get();         
        $keywords = $request->txtSearch;
        if ($keywords == "") {
            $search_product = Products::limit(0)->get();
        }
        else {
            $search_product = Products::where("ProductName","LIKE","%".$keywords."%")->get();
        }
        $category_footer = CategoryProducts::orderBy("id","DESC")->limit(9)->get();
        return view("user.shopcart", compact("categories", "cart","product_pay","search_product","category_footer"));
    }
    
    public function addCart($id, Request $request){
        $product = Products::find($id);
        $discount = Products::find($id)->discounts;
        
        if($request->txtQty){
            $qty = $request->txtQty;
        }else{
            $qty = 1;
        }
        
        $price = $product->Price;
        
        foreach($discount as $item){
            if ($item->Percent && $item->Status == 1) {
                $price = $price * (100 - $item->Percent)/100;
            }
        }
        
        $cart = [
            'id' => $id, 
            'name' => $product->ProductName,
            "qty"=>$qty , 
            "weight"=>10, 
            'price' => $price, 
            'options' => [
                'img' => $product->Picture,
                "category"=>$product->category->CategoryName,
                "price_old" => $product->Price 
                ]
            ];
            Cart::add($cart);
            // dd(Cart::content());
            return redirect()->back()->with('message','Đã mua '.$product->ProductName.' thành công');
        }
        
        /**
        * Update the specified resource in storage.
        *
        * @param  \Illuminate\Http\Request  $request
        * @param  int  $id
        * @return \Illuminate\Http\Response
        */
        public function update(Request $request, $rowId)
        {
            //
            $rowId = $request->rowId_cart;
            $qty = $request->qty;
            Cart::update($rowId,$qty);
            return redirect()->route("cart.index");
        }
        
        /**
        * Remove the specified resource from storage.
        *
        * @param  int  $id
        * @return \Illuminate\Http\Response
        */
        public function destroy($rowId)
        {
            //
            Cart::remove($rowId);
            return redirect()->route("cart.index")->with("message","Đã xóa sản phẩm trong giỏ hàng thành công");
        }


        public function updateAll(Request $request)
        {
            dd(Cart::content());
            // foreach(Cart::content() as $row) {
            //     Cart::update($row->rowId, $request->qty);
            // }
            // return redirect()->route("cart.index");
        }
        
        
    }
    

resources/views/admin/user/add_user.blade.php
@extends('layouts.admin')
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Thêm người dùng</p>
<div class="right__formWrapper">
    <form role="form" action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="right__inputWrapper">
            <label for="title">UserName</label>
            <input type="text" class="form-control" name="txtName" placeholder="UserName" required>
        </div>
        <div class="right__inputWrapper">
            <label for="date">Password</label>
            <input type="password" class="form-control" name="txtpw" id="" required>
        </div>
        <div class="right__inputWrapper">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="txtemail" placeholder="Email" required>
        </div>
        <div class="right__inputWrapper">
            <label for="txtsdt">Số điện thoại</label>
            <input type="text" class="form-control" name="txtsdt" placeholder="Số điện thoại" required>
        </div>
        <div class="right__inputWrapper">
            <label for="txtsdt">Địa chỉ</label>
            <input type="text" class="form-control" name="txtad" placeholder="Địa chỉ" required>
        </div>
        <div class="right__inputWrapper">
            <label for="p_category">Trạng thái</label>
            <select name="slstt" class="form-control form-control-sm">
                <option value="1">Hoạt động</option>
                <option value="0">Ngừng</option>
            </select>
        </div>
        <button class="btn btn-info" type="submit">Thêm</button>
    </form>
</div>
@endsection

resources/views/admin/user/edit_user.blade.php
@extends('layouts.admin')
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Cập nhật người dùng</p>
<div class="right__formWrapper">
    <form role="form" action="{{ route('user.update', $db->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method("PUT")
        <div class="right__inputWrapper">
            <label for="title">UserName</label>
            <input type="text" class="form-control" name="txtName" value="{{ $db->username }}" placeholder="UserName" required>
        </div>
        <div class="right__inputWrapper">
            <label for="date">Password</label>
            <input type="text" class="form-control" value="{{ $db->password }}" name="txtpw" id="" required>
        </div>
        <div class="right__inputWrapper">
            <label for="p_category">Quyền</label>
            <select name="sl_role" class="form-control form-control-sm">
                <option value="{{ $db->role->id }}" selected>{{ $db->role->name }}</option>
                @foreach($role as $r)
                     <option value="{{ $r->id }}">{{ $r->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="right__inputWrapper">
            <label for="p_category">Trạng thái</label>
            <select name="slstt" class="form-control form-control-sm">
                <option value="0" {{ $db->status==0?"":"selected"}}>Ngừng</option>
                <option value="1" {{ $db->status==0?"":"selected"}}>Hoạt Động</option>
            </select>
        </div>
        <button class="btn btn-info" type="submit">Cập nhật</button>
    </form>
</div>
@endsection

resources/views/admin/user/users.blade.php
@extends("layouts.admin")
@section('admin_content')
<div class="right__title">Bảng điều khiển</div>
<p class="right__desc">Xem người dùng</p>
<div class="right__search">
    <form role="form" action="/search_user" method="get">
       @csrf
        <input  style="width: 250px;" type="search" class="search" class="form-control"  name="txtSearch" id="" placeholder="Tìm theo mã, tên người dùng, quyền, ngày tạo" title="Tìm theo mã, tên người dùng, quyền, ngày tạo" >
        <input type="submit" class="button" value="Tìm kiếm" title="Tìm theo mã, tên người dùng, quyền, ngày tạo">
    </form>
</div>   
<?php
    use Illuminate\Support\Facades\Session;
    $message = Session::get('message');
    if($message){
        echo '<span style="color: red">'.$message.'</span>';
        Session::put('message',null);
    }
?>   
<div class="right__table">
    <div class="right__tableWrapper">
    @php
        $tt = 1;
    @endphp
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã người dùng</th>
                    <th>Tên người dùng</th>
                    <th>Quyền</th>
                    <th>Ngày tạo</th>
                    <th>Trạng thái</th>
                    <th>Sửa</th>
                    <th>Xoá</th>
                </tr>
            </thead>
    
            <tbody>
                @foreach($db as  $r)
                    <tr>
                        <td>{{ $tt++ }}</td>
                        <td data-label="Mã">{{ $r->id }}</td>
                        <td data-label="Tên người dùng" style="text-align:left">{{ $r->username }}</td>
                        <td data-label="Quyền"> 
                            @if( $r->role->name == 'user')
                                 <a href="#" class="label label-warning">User</a>
                            @else
                                <a href="#" class="label-success label">Admin</a>
                            @endif
                        </td>
                        <td data-label="Ngày tạo">{{ \Carbon\Carbon::parse($r->created_at)->format('d/m/Y') }}</td>
                        <td data-label="Trạng thái">
                            <!-- <input type="checkbox" name="cbtt" value="{{ $r->status }}" {{ $r->status==0?'':'checked'}}  > -->
                            @if( $r->status == 0)
                                 <a href="#" class="label label-warning">Ngừng</a>
                            @else
                                <a href="#" class="label-success label">Hoạt Động</a>
                            @endif
                        </td>
                        <td data-label="Sửa" class="right__iconTable"><a href="{{ route('user.edit', $r->id) }}"><img src="{{asset('assets/icon-edit.svg')}}" alt=""></a></td>
                        <td data-label="Xoá" class="right__iconTable">
                            <form role="form" action="{{ route('user.destroy', $r->id) }}" method="post">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <button  type="submit" onclick="return confirm('Are you sure to delete?')"><img src="{{ asset('assets/icon-trash.svg') }}" alt=""></button>   
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<div>
    {{ $db->links() }}
</div>
@endsection